#!/bin/bash
# Quick example demonstrating how to use the API testing tools

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     Growatt API Testing - Usage Examples                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This script shows you how to test serial numbers with the Growatt API."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 1: Test an Inverter Serial Number"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./test_sn.sh ABC1234567 inverter"
echo ""
echo "Replace 'ABC1234567' with your actual inverter serial number."
echo "Inverter SNs are 10 characters: 3 prefix + 7 alphanumeric"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 2: Test a Battery Serial Number"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./test_sn.sh XYZ1234567890123 battery"
echo ""
echo "Replace 'XYZ1234567890123' with your actual battery serial number."
echo "Battery SNs are 16 characters: 3 prefix + 13 alphanumeric"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 3: Test Without Device Type"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command:"
echo "  ./test_sn.sh ABC1234567"
echo ""
echo "If you don't know the device type, you can omit it."
echo "The system will accept any valid format (10 or 16 characters)."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EXAMPLE 4: Using Python Console"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Commands:"
echo "  cd /workspace/development/frappe-bench"
echo "  bench --site dev.localhost console"
echo ""
echo "Then in Python console:"
echo "  >>> from frappe_agt.utils import validate_serial_number, get_growatt_sn_info"
echo "  >>> "
echo "  >>> # Validate format"
echo "  >>> is_valid = validate_serial_number('ABC1234567', type='inverter')"
echo "  >>> print(f'Valid: {is_valid}')"
echo "  >>> "
echo "  >>> # Get device info from API"
echo "  >>> device_info = get_growatt_sn_info('ABC1234567')"
echo "  >>> if device_info:"
echo "  >>>     print(f\"Model: {device_info['data']['model']}\")"
echo "  >>>     print(f\"Warranty: {device_info['data']['warrantyTime']} years\")"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "WHAT YOU'LL SEE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Sample output:"
echo ""
echo "  Step 1: Validating serial number format..."
echo "    Format: ✓ VALID"
echo "    Type: inverter"
echo ""
echo "  Step 2: Fetching from Growatt API..."
echo "    ✓ API Response Received"
echo ""
echo "  Response Details:"
echo "    Code: 200"
echo "    Message: success"
echo ""
echo "  Device Information:"
echo "    deviceSN: ABC1234567"
echo "    model: MID 25KTL3-X"
echo "    deliveryTime: 2024-01-15"
echo "    warrantyTime: 10 years"
echo "    ..."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "READY TO TEST!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Provide your serial number(s) and run:"
echo "  cd /workspace/development/frappe-bench/apps/frappe_agt"
echo "  ./scripts/test_sn.sh YOUR_SERIAL_NUMBER inverter"
echo ""
echo "For detailed documentation, see:"
echo "  • TESTING.md - Complete testing guide"
echo "  • README.md - Quick start and usage guide"
echo ""
